/**
 * Generates the plain-CSS `:root { --nd-*: ... }` block from the canonical
 * tokens (issue #53). Consumed by app/scripts/generate-tokens-css.mjs to emit
 * app/src/tokens.css (PWA-first: the CSS file is committed, no JS runtime).
 *
 * Type-only import — the module has zero runtime dependencies, so jiti can
 * load it from the generator script without a bundler.
 */
import type { tokens } from "./tokens";

/** Canonical focus ring spec (docs/design/05-design-tokens.md §10). */
const FOCUS_WIDTH = "2px";
const FOCUS_OFFSET = "2px";

/** `nd-`-prefixed token key → bare CSS var suffix (`nd-fast` → `fast`). */
function bareKey(key: string): string {
  return key.startsWith("nd-") ? key.slice(3) : key;
}

/**
 * Builds the full `:root` rule for the design tokens.
 *
 * Emits, in order: the 10 semantic colors, both radii, the 5 hairline
 * shadows, the 4 motion durations, the 3 z-index layers, the touch target,
 * the scanline effect and the focus ring (color derived from
 * `colors["nd-cyan"]` — the functional white-light channel).
 *
 * @param t The canonical {@link tokens} object.
 * @returns The exact CSS text written to `app/src/tokens.css`.
 */
export function buildTokensCss(t: typeof tokens): string {
  const rules: string[] = [];

  for (const [key, value] of Object.entries(t.colors)) {
    rules.push(`  --${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(t.borderRadius)) {
    rules.push(`  --nd-radius-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(t.boxShadow)) {
    rules.push(`  --nd-shadow-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(t.transitionDuration)) {
    rules.push(`  --nd-duration-${bareKey(key)}: ${value};`);
  }

  for (const [key, value] of Object.entries(t.zIndex)) {
    rules.push(`  --nd-z-${bareKey(key)}: ${value};`);
  }

  rules.push(`  --nd-touch-target: ${t.minHeight.touch};`);
  rules.push(`  --nd-scanline: ${t.effects.scanline};`);
  rules.push(`  --nd-focus-color: ${t.colors["nd-cyan"]};`);
  rules.push(`  --nd-focus-width: ${FOCUS_WIDTH};`);
  rules.push(`  --nd-focus-offset: ${FOCUS_OFFSET};`);

  return (
    "/* GENERATED by app/scripts/generate-tokens-css.mjs — do not edit by hand. */\n" +
    "/* Canonical source: app/src/lib/tokens.ts. Run `npm run tokens:generate`. */\n" +
    ":root {\n" +
    rules.join("\n") +
    "\n}\n"
  );
}
